modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="ftbconv"
version="${file.jarVersion}"
displayName="FTB quest lang converter"
description=''' Stuff '''

[[dependencies.ftbconv]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbconv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"