modLoader = "javafml"
loaderVersion = "[36,)"
license = "CC-BY-4.0"

[[mods]]
modId = "ftbqlocalkeys"
version = "${version}"
displayName = "FTBQLocalizationKeys-Reconverted"
displayURL="https://github.com/LocalizedMC/FTBQLocalizationkeys"
logoFile="icon.png" #optional
credits="BlackAuresArt"
authors="TexTrue, LocalizedMC, BocchiKessokuTeam"
description = '''
FTB Quest lang converter
'''
